--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Debian 14.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.4 (Debian 14.4-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.address (
    id bigint NOT NULL,
    name character varying(255),
    latitude character varying(255),
    longitude character varying(255)
);


ALTER TABLE public.address OWNER TO qgasosa;

--
-- Name: address_id_seq; Type: SEQUENCE; Schema: public; Owner: qgasosa
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.admin (
    id bigint NOT NULL,
    username character varying(255),
    password character varying(255)
);


ALTER TABLE public.admin OWNER TO qgasosa;

--
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: qgasosa
--

ALTER TABLE public.admin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO qgasosa;

--
-- Name: fuel; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.fuel (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.fuel OWNER TO qgasosa;

--
-- Name: fuel_id_seq; Type: SEQUENCE; Schema: public; Owner: qgasosa
--

ALTER TABLE public.fuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gas_station; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.gas_station (
    id bigint NOT NULL,
    name character varying(255),
    address_id bigint
);


ALTER TABLE public.gas_station OWNER TO qgasosa;

--
-- Name: gas_station_fuel; Type: TABLE; Schema: public; Owner: qgasosa
--

CREATE TABLE public.gas_station_fuel (
    id bigint NOT NULL,
    gas_station_id bigint,
    fuel_id bigint,
    price double precision,
    updated_at timestamp without time zone
);


ALTER TABLE public.gas_station_fuel OWNER TO qgasosa;

--
-- Name: gas_station_fuel_id_seq; Type: SEQUENCE; Schema: public; Owner: qgasosa
--

ALTER TABLE public.gas_station_fuel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gas_station_fuel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gas_station_id_seq; Type: SEQUENCE; Schema: public; Owner: qgasosa
--

ALTER TABLE public.gas_station ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gas_station_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.address (id, name, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.admin (id, username, password) FROM stdin;
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1.1	create and alter tables	SQL	V1_1__create_and_alter_tables.sql	507338874	qgasosa	2022-07-30 18:16:59.952767	18	t
2	1.2	create address table	SQL	V1_2__create_address_table.sql	-1242352173	qgasosa	2022-07-30 18:16:59.985181	8	t
3	1.3	drop gas station id from address	SQL	V1_3__drop_gas_station_id_from_address.sql	1073006460	qgasosa	2022-07-30 18:17:00.003196	4	t
4	1.4	add updated at to gas station fuel	SQL	V1_4__add_updated_at_to_gas_station_fuel.sql	1337378857	qgasosa	2022-07-30 18:17:00.0161	3	t
\.


--
-- Data for Name: fuel; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.fuel (id, name) FROM stdin;
\.


--
-- Data for Name: gas_station; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.gas_station (id, name, address_id) FROM stdin;
\.


--
-- Data for Name: gas_station_fuel; Type: TABLE DATA; Schema: public; Owner: qgasosa
--

COPY public.gas_station_fuel (id, gas_station_id, fuel_id, price, updated_at) FROM stdin;
\.


--
-- Name: address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: qgasosa
--

SELECT pg_catalog.setval('public.address_id_seq', 1, false);


--
-- Name: admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: qgasosa
--

SELECT pg_catalog.setval('public.admin_id_seq', 1, false);


--
-- Name: fuel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: qgasosa
--

SELECT pg_catalog.setval('public.fuel_id_seq', 1, false);


--
-- Name: gas_station_fuel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: qgasosa
--

SELECT pg_catalog.setval('public.gas_station_fuel_id_seq', 1, false);


--
-- Name: gas_station_id_seq; Type: SEQUENCE SET; Schema: public; Owner: qgasosa
--

SELECT pg_catalog.setval('public.gas_station_id_seq', 1, false);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: address pk_address; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT pk_address PRIMARY KEY (id);


--
-- Name: admin pk_admin; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT pk_admin PRIMARY KEY (id);


--
-- Name: fuel pk_fuel; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.fuel
    ADD CONSTRAINT pk_fuel PRIMARY KEY (id);


--
-- Name: gas_station pk_gasstation; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.gas_station
    ADD CONSTRAINT pk_gasstation PRIMARY KEY (id);


--
-- Name: gas_station_fuel pk_gasstationfuel; Type: CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.gas_station_fuel
    ADD CONSTRAINT pk_gasstationfuel PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: qgasosa
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: gas_station fk_gasstation_on_address; Type: FK CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.gas_station
    ADD CONSTRAINT fk_gasstation_on_address FOREIGN KEY (address_id) REFERENCES public.address(id);


--
-- Name: gas_station_fuel fk_gasstationfuel_on_fuel; Type: FK CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.gas_station_fuel
    ADD CONSTRAINT fk_gasstationfuel_on_fuel FOREIGN KEY (fuel_id) REFERENCES public.fuel(id);


--
-- Name: gas_station_fuel fk_gasstationfuel_on_gas_station; Type: FK CONSTRAINT; Schema: public; Owner: qgasosa
--

ALTER TABLE ONLY public.gas_station_fuel
    ADD CONSTRAINT fk_gasstationfuel_on_gas_station FOREIGN KEY (gas_station_id) REFERENCES public.gas_station(id);


--
-- PostgreSQL database dump complete
--

