CREATE TABLE IF NOT EXISTS address
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    latitude       VARCHAR(255),
    longitude      VARCHAR(255),
    gas_station_id BIGINT,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

ALTER TABLE gas_station
    ADD address_id BIGINT;

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_GASSTATION FOREIGN KEY (gas_station_id) REFERENCES gas_station (id);

ALTER TABLE gas_station
    ADD CONSTRAINT FK_GASSTATION_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE gas_station
    DROP COLUMN address;
